<?php
/**
 * scripts/ftp_deploy.php
 *
 * Uploads suche to a remote FTP server, then runs pending DB migrations via
 * a temporary self-deleting PHP runner served from the webroot.
 *
 * Reads credentials from suche/config.yaml (generated by mcp/generate.py).
 * Regenerate for the desired target before running:
 *
 *   python3 ../mcp/generate.py --app suche --target world4you
 *   php scripts/ftp_deploy.php
 */

use Symfony\Component\Yaml\Yaml;

$root = dirname(__DIR__);
require_once $root . '/vendor/autoload.php';

$cfg = Yaml::parseFile($root . '/config.yaml');

$deploy = $cfg['deploy'] ?? [];
foreach (['ftp_host', 'ftp_user', 'ftp_password', 'ftp_base_dir'] as $k) {
    if (empty($deploy[$k])) {
        fwrite(STDERR, "config.yaml is missing deploy.$k — regenerate with mcp/generate.py --app suche --target world4you\n");
        exit(1);
    }
}

$ftpServer  = $deploy['ftp_host'];
$ftpUser    = $deploy['ftp_user'];
$ftpPass    = $deploy['ftp_password'];
$remoteBase = rtrim($deploy['ftp_base_dir'], '/');
$baseUrl    = rtrim($cfg['app']['base_url'] ?? '', '/');
$target     = $cfg['target'] ?? 'world4you';

if ($baseUrl === '') {
    fwrite(STDERR, "config.yaml is missing app.base_url\n");
    exit(1);
}

// ── Exclude rules ─────────────────────────────────────────────────────────────
//
// db/migrations/ stays on the server (the migration runner needs it).
// scripts/ is excluded — deploy tooling doesn't belong on a web server.
// Dev-only vendor packages are excluded by directory name (matched at any depth).

$excludeDirs = [
    '.git', '.claude', 'tests', 'deprecated', 'docs',
    'data', 'backups', '.worktrees', 'worktrees', 'Archiv',
    'scripts',
    // dev-only vendor packages
    'phpunit', 'sebastian', 'nikic', 'theseer', 'phar-io', 'myclabs', 'staabm',
    // vendor CLI binaries
    'bin',
];
$excludeRootDirs = [];

$excludeNames = [
    '.gitignore', '.DS_Store', '.phpunit.result.cache',
    'CLAUDE.md', 'phpunit.xml', 'composer.json', 'composer.lock',
    'config.example.yaml', 'update.md',
];
$excludeExts = ['md'];

// ── Regenerate composer autoloader without dev deps ──────────────────────────

$composerBin = null;
foreach ([getenv('HOME') . '/bin/composer', '/opt/homebrew/bin/composer', '/usr/local/bin/composer'] as $cand) {
    if (is_executable($cand)) { $composerBin = $cand; break; }
}
if ($composerBin === null) {
    fwrite(STDERR, "composer not found — install it or adjust ftp_deploy.php\n");
    exit(1);
}

function run_composer(string $bin, string $cwd, array $args): int {
    $descriptors = [0 => ['pipe', 'r'], 1 => STDOUT, 2 => STDERR];
    $proc = proc_open(array_merge([$bin], $args), $descriptors, $pipes, $cwd);
    if (!is_resource($proc)) return 1;
    fclose($pipes[0]);
    return proc_close($proc);
}

echo "Dumping prod autoloader (--no-dev) ...\n";
if (run_composer($composerBin, $root, ['dump-autoload', '--no-dev', '-o']) !== 0) {
    fwrite(STDERR, "composer dump-autoload --no-dev failed\n");
    exit(1);
}

register_shutdown_function(function () use ($root, $composerBin) {
    echo "\nRestoring dev autoloader ...\n";
    run_composer($composerBin, $root, ['dump-autoload', '-o']);
});

// ── Connect ───────────────────────────────────────────────────────────────────

echo "Connecting to $ftpServer ...\n";
$ftp = ftp_ssl_connect($ftpServer) ?: ftp_connect($ftpServer);
if (!$ftp) {
    fwrite(STDERR, "Could not connect to $ftpServer.\n");
    exit(1);
}
if (!ftp_login($ftp, $ftpUser, $ftpPass)) {
    fwrite(STDERR, "FTP login failed for user $ftpUser.\n");
    exit(1);
}
ftp_pasv($ftp, true);
echo "Connected. Target: $remoteBase ($target)\n\n";

// ── Helpers ───────────────────────────────────────────────────────────────────

function ftp_mkdirs(mixed $ftp, string $remotePath): void {
    $parts = explode('/', trim($remotePath, '/'));
    $path  = '';
    foreach ($parts as $part) {
        $path .= '/' . $part;
        @ftp_mkdir($ftp, $path);
    }
}

function upload_tree(
    mixed  $ftp,
    string $localDir,
    string $remoteDir,
    string $relPath,
    array  $excludeDirs,
    array  $excludeRootDirs,
    array  $excludeNames,
    array  $excludeExts,
    int    &$uploaded,
    int    &$failed
): void {
    ftp_mkdirs($ftp, $remoteDir);

    foreach (scandir($localDir) as $item) {
        if ($item === '.' || $item === '..') continue;

        $localPath  = $localDir  . '/' . $item;
        $remotePath = $remoteDir . '/' . $item;
        $itemRel    = $relPath === '' ? $item : $relPath . '/' . $item;

        if (is_dir($localPath)) {
            if (in_array($item, $excludeDirs, true)) continue;
            if ($relPath === '' && in_array($item, $excludeRootDirs, true)) continue;
            upload_tree(
                $ftp, $localPath, $remotePath, $itemRel,
                $excludeDirs, $excludeRootDirs, $excludeNames, $excludeExts,
                $uploaded, $failed
            );
        } else {
            if (in_array($item, $excludeNames, true)) continue;
            if (in_array(pathinfo($item, PATHINFO_EXTENSION), $excludeExts, true)) continue;

            if (ftp_put($ftp, $remotePath, $localPath, FTP_BINARY)) {
                echo "  ok  $remotePath\n";
                $uploaded++;
            } else {
                fwrite(STDERR, "  FAIL $remotePath\n");
                $failed++;
            }
        }
    }
}

// ── Upload files ──────────────────────────────────────────────────────────────

$uploaded = 0;
$failed   = 0;

upload_tree(
    $ftp, $root, $remoteBase, '',
    $excludeDirs, $excludeRootDirs, $excludeNames, $excludeExts,
    $uploaded, $failed
);

// ── Upload temporary migration runner ─────────────────────────────────────────
// Self-contained: reads ../config.yaml via symfony/yaml on the server, runs
// pending db/migrations/*.sql against s_db_migrations, self-deletes.

$token = bin2hex(random_bytes(16));

$runner = <<<'RUNNER'
<?php
if (($_GET['t'] ?? '') !== '__TOKEN__') { http_response_code(403); exit; }
$r = dirname(__DIR__);
require_once $r . '/vendor/autoload.php';
$cfg = \Symfony\Component\Yaml\Yaml::parseFile($r . '/config.yaml');
$db  = $cfg['db'];
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$con = mysqli_connect($db['host'], $db['user'], $db['password'], $db['name']);
mysqli_set_charset($con, 'utf8mb4');
$con->query("CREATE TABLE IF NOT EXISTS s_db_migrations (
    id         INT UNSIGNED NOT NULL AUTO_INCREMENT,
    filename   VARCHAR(128) NOT NULL,
    applied_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_filename (filename)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$applied = [];
$res = $con->query('SELECT filename FROM s_db_migrations');
while ($row = $res->fetch_assoc()) $applied[$row['filename']] = true;
$files = glob($r . '/db/migrations/*.sql') ?: []; sort($files); $ran = 0;
foreach ($files as $file) {
    $name = basename($file);
    if (isset($applied[$name])) { echo "skip $name\n"; continue; }
    $sql = file_get_contents($file);
    $sql = preg_replace('/^\s*USE\s+\S+\s*;\s*$/im', '', $sql);
    $sql = preg_replace('/\bADD COLUMN IF NOT EXISTS\b/i', 'ADD COLUMN', $sql);
    $sql = preg_replace('/\bADD INDEX IF NOT EXISTS\b/i', 'ADD INDEX', $sql);
    try {
        $con->multi_query($sql);
        do { if ($result = $con->store_result()) $result->free(); }
        while ($con->more_results() && $con->next_result());
    } catch (\mysqli_sql_exception $e) {
        // errno 1060 = duplicate column, 1061 = duplicate key — idempotent
        if (!in_array($e->getCode(), [1060, 1061], true)) {
            echo "FAIL $name: " . $e->getMessage() . "\n"; unlink(__FILE__); exit;
        }
    }
    $stmt = $con->prepare('INSERT INTO s_db_migrations (filename) VALUES (?)');
    $stmt->bind_param('s', $name); $stmt->execute(); $stmt->close();
    echo "apply $name\n"; $ran++;
}
echo $ran === 0 ? "Nothing to migrate.\n" : "$ran migration(s) applied.\n";
unlink(__FILE__);
RUNNER;

$runner = str_replace('__TOKEN__', $token, $runner);
$tmp = tempnam(sys_get_temp_dir(), 'suche_');
file_put_contents($tmp, $runner);

$runnerRemote = $remoteBase . '/web/_m.php';
if (ftp_put($ftp, $runnerRemote, $tmp, FTP_BINARY)) {
    echo "  ok  $runnerRemote (migration runner)\n";
}
unlink($tmp);

ftp_close($ftp);

// ── Trigger migration runner via HTTP ─────────────────────────────────────────

$ctx = stream_context_create([
    'ssl'  => ['verify_peer' => false, 'verify_peer_name' => false],
    'http' => ['timeout' => 60, 'follow_location' => 1],
]);

echo "\nRunning migrations on server ...\n";
$urls = [$baseUrl . '/_m.php?t=' . $token];
if (str_starts_with($baseUrl, 'https://')) {
    $urls[] = 'http://' . substr($baseUrl, 8) . '/_m.php?t=' . $token;
}
$response = false;
foreach ($urls as $url) {
    $response = @file_get_contents($url, false, $ctx);
    if ($response !== false) { echo "  ($url)\n"; break; }
    fwrite(STDERR, "  could not reach $url, trying next ...\n");
}
if ($response !== false) {
    foreach (explode("\n", trim($response)) as $line) {
        echo "  $line\n";
    }
} else {
    fwrite(STDERR, "  Warning: migration runner could not be triggered.\n");
    fwrite(STDERR, "  Run this once in a browser: $baseUrl/_m.php?t=$token\n");
}

echo "\nDone. $uploaded uploaded" . ($failed ? ", $failed FAILED" : '') . ".\n";
if ($failed > 10) exit(1);
